//This macro segments snake nuclei blood smears to obtain the total cell count.
// Cell count includes all cell types, although larger WBCs may be filtered out.
// Note that the segmentation works in part by identifying RBC nuclie and will not work for species with 
// non-nucleated RBCs.
//Dependencies:
// Segmentation uses probabilities generated by an Ilastik .ilp file.
// You must have Ilastik installed (doesn't need to be open) on your computer, the Ilastik plug-ins installed in ImageJ,
// and the correct executable location identified (see this website for more information:
// https://github.com/ilastik/ilastik4ij?tab=readme-ov-file#configuration-for-running-ilastik-from-within-Fiji.
// You must also have MorphoLibJ plugins installed: https://github.com/ijpb/MorphoLibJ
//
//This contains an adaptation of a white balance correction written by Patrice Mascalchi (2014, Univ. of Cambridge, UK):
//   https://github.com/pmascalchi/ImageJ_Auto-white-balance-correction
// Which was, in turn, modified from code by Vytas Bindokas (2006, Univ. of Chicago, USA)
//
//Kristopher Kubow (James Madison University, USA)
//  v1: 2024-08-01
//  v2: 2024-10-29 - implemented white balance correction and retuned segmentation to handle larger staining variation


// Clean-up before we start...
close("*");
roiManager("reset");

//User Input
#@ File (label = "Choose file to analyze", style = "file") inputFile   //this is the color blood smear image
#@ File (label = "Select the Ilastik Segmentation File", style = "file") ilastikFile  //this is the Ilastik .ilp file

//Open the original image an rename
open(inputFile);
rename("original");


//*************** White Balance ***************//
setTool("rectangle");

waitForUser("Draw a region over a background area.");   //ask user to sample background with an ROI
if (selectionType==-1) exit("You must draw a region first.");  //defensive coding

run("Select None");  //de-selects ROI - have to do this or only the ROI will be duplicated
run("Duplicate...", "title=balanced");  //make temp image for manipulations
run("RGB Stack");          //separate RGB components
run("Restore Selection");  //re-selects ROI

//measure background RGB values
run("Set Measurements...", "  mean redirect=None decimal=3");
val = newArray(3);
for (s=1;s<=3;s++) {
	setSlice(s);
	run("Measure");
	val[s-1] = getResult("Mean");
}
Array.getStatistics(val, min, max, mean); //calculate mean background RGB value

run("Select None");  //de-select ROI
run("32-bit");  //convert to 32-bit for greater precision

//adjust all values by deviation of mean background from mean RGB value
for (s=1; s<=3; s++) {
	setSlice(s);
	dR = val[s-1] - mean;
	if (dR < 0) {
		run("Add...", "slice value="+ abs(dR));
	} else if (dR > 0) {
		run("Subtract...", "slice value="+ abs(dR));
	}
}

//convert "balanced (RGB)" back to RGB image and clean-up the other files
run("16-bit");
run("Convert Stack to RGB"); 
selectWindow("Results"); 
run("Close");
close("balanced");
close("original");

//************** Segmentation ******************//
//Generate a probability image using the Ilastik file
type = "Probabilities";
run("Run Pixel Classification Prediction", "projectfilename=[" + ilastikFile + "] input=[balanced (RGB)] pixelclassificationtype=[" + type + "]");
rename("probability");

//Use only the first "channel" which corresponds to the cell component.
// Channel 2 corresponds to the cytoplasm. Channel 3 corresponds to the background.
selectImage("probability");
run("Duplicate...", "title=image");  //this just duplicates the first channel
selectImage("image");
run("Grays");    //not really necessary but made things easier when debugging

setBatchMode(true);

//Segment probability image by thresholding
setAutoThreshold("Default dark");
setOption("BlackBackground", true);
run("Convert to Mask");
run("Convert to Mask");  //for some reason sometimes the first time doesn't work

//Clean-up the segmentation and use Analyze Particles to generate ROIs and cell count
run("Morphological Filters", "operation=Opening element=Square radius=2");
run("Gray Scale Attribute Filtering", "operation=Opening attribute=Area minimum=100 connectivity=4");
run("Morphological Filters", "operation=Dilation element=Square radius=1");
//run("Analyze Particles...", "size=100-2000 show=[Overlay Masks] exclude add");
run("Analyze Particles...", "size=400-2000 show=Nothing exclude summarize add");  //we're excluding on edges; size excludes most heterophils

setBatchMode(false);

//Apply the ROIs to the original image so we can compare and see if there were any mistakes
selectImage("balanced (RGB)");
roiManager("Show All");

//Clean things up...
close("image");  
close("probability");
close("image-Opening-attrFilt-Dilation");
